//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using CrystalDecisions.CrystalReports.Engine;

namespace CrystalDecisions.Web
{
    public class CrystalReportViewer
    {
        public ReportDocument ReportSource { get; internal set; }
    }
}